# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

# This Dockerfile is used to build the APSVIZ-Msg-Handler image

# leverage the renci python base image
FROM python:3.12.7-slim

# update the image base
RUN apt-get update && apt-get upgrade
# RUN apt-get install -y procps

# clear the apt cache
RUN apt-get clean

# set up requirements
WORKDIR /repo/APSVIZ-Msg-Handler

# Normal requirements
ADD requirements.txt .
RUN pip install -r requirements.txt

# Copy in the rest of the code
COPY src src
COPY .pylintrc .pylintrc
COPY ./test/*.py test/
COPY ./test/test_files test/test_files/

#ENV LOG_PATH /data/logs
#ENV TESTDATA_PATH /data/tmp
ENV PYTHONPATH="/repo/APSVIZ-Archiver/src:/repo/APSViz-Msg-Handler/test:$PYTHONPATH"

# start the tests
# CMD pytest